version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/restaurant

  alembic:
    build: .
    depends_on:
      - db
    command: alembic upgrade head
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/restaurant

volumes:
  postgres_data:
